spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: auth
        # dialect: com.tth.auth.configuration.hibernate.CustomPostgreSQLDialect
  flyway:
    enabled: true
    schemas: auth
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # jackson:
  #   serialization:
  #     write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: ${ENABLED_API_DOCS:false}
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

setting:
  default-user-password: ${DEFAULT_USER_PASSWORD:123456}
  admin-user:
    username: ${ADMIN_USERNAME:superadmin}
    password: ${ADMIN_PASSWORD:123456}
